name: Scrape listings (Pararius, per stad)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/30 * * * *" # elke 30 minuten

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    strategy:
      fail-fast: false
      matrix:
        city: [amsterdam, rotterdam, utrecht]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Run scraper (matrix)
        env:
          CITY: ${{ matrix.city }}
          INGEST_URL: ${{ secrets.INGEST_ENDPOINT }}
          INGEST_SECRET: ${{ secrets.INGEST_SECRET }}
        run: |
          npm run scrape
