name: Scrape listings (Pararius)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/30 * * * *"  # elke 30 minuten

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          check-latest: true   # geen cache hier -> voorkomt lockfile error

      - name: Install deps
        run: npm ci || npm i

      - name: Install Playwright (browsers + dependencies)
        run: npx playwright install --with-deps chromium

      - name: Run scraper
        env:
          INGEST_URL: ${{ secrets.INGEST_URL }}
          INGEST_SECRET: ${{ secrets.INGEST_SECRET }}
        run: npm run scrape
