name: Scrape listings (Pararius)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "5 */6 * * *"  # elke 6 uur, op minuut 5

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci || npm i

      - name: Run scraper
        env:
          INGEST_URL: ${{ secrets.INGEST_URL }}      # zet je live /api/ingest url in repo secrets
          INGEST_SECRET: ${{ secrets.INGEST_SECRET }}# zet je ingest secret in repo secrets
        run: npm run scrape
