name: Scrape listings (Pararius, per stad)

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        city: [amsterdam, rotterdam, utrecht]  # breid later uit
    concurrency:
      group: scrape-pararius-${{ matrix.city }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npx playwright install --with-deps chromium
      - name: Run scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          INGEST_ENDPOINT: ${{ secrets.INGEST_ENDPOINT }}
          INGEST_SECRET: ${{ secrets.INGEST_SECRET }}
          CITY: ${{ matrix.city }}
          DETAIL_LIMIT: "20"
          NAV_TIMEOUT_MS: "12000"
        run: npm run scrape
